---
# tasks file for setup-nfs-server
- name: Install NFS Packages
  apt:
    name:
      - nfs-kernel-server
    state: present
  
- name: Create /nfs directory
  ansible.builtin.file:
    path: /nfs
    state: directory
    mode: '0755'

- name: Copy Export Config
  copy:
    src: exports
    dest: /etc/exports
  notify: Restart NFS

