---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - basic-packages
    - set-timezone
    - flush-iptables
    - install-k8s

- hosts: masters
  become: yes
  roles:
    - setup-nfs-server
    - init-k8s-cluster

- hosts: workers
  become: yes
  roles:
    - join-k8s-cluster

- hosts: masters
  become: yes
  roles:
    - setup-k8s-cluster

- name: Fetch kube config
  hosts: k8slab_instance-0
  gather_facts: no
  tasks:
  - name: Fetch kube config
    become: yes
    ansible.builtin.fetch:
      src: /root/.kube/config
      dest: ../
      flat: yes

