---
# tasks file for init-k8s-cluster
- name: Remove old cluster
  command: kubeadm reset --force

- name: Initialize new cluster
  command: kubeadm init --ignore-preflight-errors=NumCPU --control-plane-endpoint "{{ ansible_host }}:6443"

- name: Create .kube dir
  file:
    path: ~/.kube
    state: directory

- name: Link admin.conf to ~/.kube/config
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link

- name: Fetch kube config
  become: yes
  ansible.builtin.fetch:
    src: /root/.kube/config
    dest: ../
    flat: yes

- name: Wait for port 6443 to become open
  ansible.builtin.wait_for:
    host: localhost
    port: 6443
    delay: 10

- name: Getting join command from the master node…
  command: kubeadm token create --print-join-command
  register: join_command

- name: Setting join command fact
  set_fact:
    join_command: "{{ join_command.stdout_lines[0] }}"


