---
# handlers file for install-k8s
- name: Restart Containerd
  become: true
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Load Kernel Modules
  shell: modprobe overlay && modprobe br_netfilter

- name: Apply Required Sysctl
  shell: sysctl --system

